name: "PoopMap Stats"
description: "Show your poops from PoopMap in a nice graph"
branding:
  icon: user-check
  color: gray-dark
  
inputs:
  pat:
    description: "A GitHub personal access token (PAT) that includes all 'repo' scopes"
    required: true
    default: ""

  username:
    description: "Your PoopMap username"
    required: true
    default: ""

  password:
    description: "Your PoopMap password"
    required: true
    default: ""
    
outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: "node12"
  main: "index.js"
